name       : haskell-hxt-regex-xmlschema
version    : 9.2.0.3
release    : 3
source     :
    - https://hackage.haskell.org/package/hxt-regex-xmlschema-9.2.0.3/hxt-regex-xmlschema-9.2.0.3.tar.gz : f4743ba65498d6001cdfcf5cbc3317d4bc43941be5c7030b60beb83408c892b0
license    : MIT
component  : programming.haskell
summary    : This library supports full W3C XML Schema regular expressions inclusive all Unicode character sets and blocks.
description: |
    This library supports full W3C XML Schema regular expressions inclusive all Unicode character sets and blocks.
builddeps  :
    - haskell-cabal-install
    - haskell-hxt-charproperties-devel
rundeps    :
    - devel:
        - haskell-hxt-charproperties-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
